In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
bremtoil_data = pd.read_csv('data\\raw\\ins_data\\brentoil_data.csv')
fdi_data = pd.read_csv('data\\raw\\ins_data\\fdi_data.csv', delimiter='\t')
gas_data = pd.read_csv('data\\raw\\ins_data\\henryhub_gas_data.csv')
im_exp_data = pd.read_csv('data\\raw\\ins_data\\im_ex_data.csv', delimiter='\t')
castlecoal_data = pd.read_csv('data\\raw\\ins_data\\newcastlecoal_data.csv')

In [7]:
display(bremtoil_data.head())
display(fdi_data.head())
display(gas_data.head())
display(im_exp_data.head())
display(castlecoal_data.head())

        Date\tPrice\tOpen\tHigh\tLow\tVol.\tChange %
0  12/1/2025\t60.85\t62.69\t64.09\t58.72\t5.09M\t...
1  11/1/2025\t63.2\t65.12\t65.32\t61.6\t5.78M\t-2...
2  10/1/2025\t65.07\t66.18\t66.78\t60.07\t7.76M\t...
3  9/1/2025\t67.02\t67.42\t70.76\t65.07\t5.45M\t-...
4   8/1/2025\t68.12\t71.83\t72\t65.01\t5.29M\t-4.99%

  Time;FDI giải ngân (lũy kế năm) (tỉ USD) (value - triệu USD);% yoy;FDI đăng kí (lũy kế năm) (tỉ USD) (value);% yoy.1;"FDI cấp mới &
0  tăng vốn (lũy kế năm) (tỉ USD)(value)";% yoy.2...
1  Dec-25;27,620;9;38,420;0.5;17,320;-12.2;7,030;...
2  Nov-25;23,600;8.9;33,690;7.4;15,960;-8.2;6,110...
3  Oct-25;21,300;8.8;31,520;15.6;14,070;-7.6;5,34...
4  Sep-25;18,800;8.5;28,540;15.2;12,400;-8.6;4,84...

         Date  Price   Open   High    Low     Vol. Change %
0  12/01/2025  3.686  4.863  5.498  3.679  367.73K  -24.00%
1  11/01/2025  4.850  4.152  4.874  4.087  239.09K   17.60%
2  10/01/2025  4.124  3.331  4.155  2.892  274.80K   24.86%
3  09/01/2025  3.303  2.984  3.350  2.772  229.09K   10.21%
4  08/01/2025  2.997  3.090  3.148  2.624  188.32K   -3.51%

                 Date;Country;Region;Export;Import
0  01/2019;A-rập Xê-út;Others;32,770.53;111,355.17
1   02/2019;A-rập Xê-út;Others;17,696.01;90,498.01
2  03/2019;A-rập Xê-út;Others;35,249.87;107,914.56
3   04/2019;A-rập Xê-út;Others;35,906.07;94,036.00
4   05/2019;A-rập Xê-út;Others;30,991.47;98,163.40

         Date   Price    Open    High    Low   Vol. Change %
0  12/01/2025  107.50  108.75  110.50  106.4  0.61K   -3.24%
1  11/01/2025  111.10  109.40  111.50  108.4  0.67K    6.67%
2  10/01/2025  104.15  105.55  105.85  103.7  0.07K   -1.93%
3  09/01/2025  106.20  109.90  110.00  100.7  0.52K   -4.75%
4  08/01/2025  111.50  114.90  114.95  110.6  0.03K   -3.17%